# Generated by Django 4.1.7 on 2023-03-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100)),
                ('type_action', models.CharField(max_length=50)),
                ('origine_action', models.CharField(max_length=50)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('domaine', models.CharField(max_length=50)),
                ('plan_action', models.TextField()),
                ('delai_mise_en_oeuvre', models.DateField()),
                ('priorite', models.IntegerField()),
                ('delai_mesure_eff', models.DateField()),
                ('type_critere_eff', models.CharField(max_length=50)),
                ('detail_critere_eff', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Danger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste_de_travail', models.CharField(max_length=255)),
                ('taches', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('consequences', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('famille_nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_realisation', models.DateField()),
                ('etat', models.CharField(max_length=50)),
                ('action_realisee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.actions')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('courrier', models.EmailField(max_length=254)),
                ('numero_tel', models.CharField(blank=True, max_length=255, null=True)),
                ('presente_vous', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('fonction', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_sip', models.CharField(blank=True, max_length=255, null=True)),
                ('othermail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('nom_tache', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('echeance', models.DateField()),
                ('description', models.TextField()),
                ('priorite', models.CharField(max_length=50)),
                ('date_realisation', models.DateField()),
                ('état', models.CharField(max_length=50)),
                ('commentaire', models.TextField()),
                ('piece_jointe', models.CharField(blank=True, max_length=500, null=True)),
                ('assigne_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.utilisateur')),
                ('realisation_associee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.realisation')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_nom', models.CharField(max_length=255)),
                ('sigle', models.CharField(max_length=255)),
                ('groupe_retso', models.CharField(max_length=255)),
                ('responsable_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Processus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255)),
                ('typologie', models.CharField(max_length=255)),
                ('sigle', models.CharField(max_length=50)),
                ('finalite', models.TextField()),
                ('acteurs', models.TextField()),
                ('donnee_entree', models.TextField()),
                ('activites', models.TextField()),
                ('donnee_sortie', models.TextField()),
                ('ressources_tech_org', models.TextField()),
                ('objectifs_ind', models.TextField()),
                ('outils_surveil', models.TextField()),
                ('pilote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='MesureEfficacite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cloture', models.DateField()),
                ('resultat_mesure_eff', models.TextField()),
                ('mesure_eff', models.TextField()),
                ('cout', models.FloatField()),
                ('action_associee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.actions')),
            ],
        ),
        migrations.CreateModel(
            name='Evenements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contract', models.CharField(max_length=255)),
                ('nom_personne', models.CharField(max_length=255)),
                ('type_evenement', models.CharField(max_length=255)),
                ('intitule', models.CharField(max_length=255)),
                ('resume', models.TextField()),
                ('temoins', models.CharField(max_length=255)),
                ('premiere_pers_info', models.CharField(max_length=255)),
                ('action_immediate', models.TextField()),
                ('date_accident', models.DateField()),
                ('periode_travail', models.CharField(max_length=255)),
                ('lieu_accident', models.CharField(max_length=255)),
                ('tache_effectue', models.CharField(max_length=255)),
                ('utiliser_chien', models.BooleanField()),
                ('siege_de_lesions_1', models.CharField(blank=True, max_length=255)),
                ('siege_de_lesions_2', models.CharField(blank=True, max_length=255)),
                ('nature_lesions', models.CharField(max_length=255)),
                ('dangers', models.ManyToManyField(to='QHSEApi.danger')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.services')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.site')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationDanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('probabilite', models.IntegerField()),
                ('severite', models.IntegerField()),
                ('frequences_exposition', models.IntegerField()),
                ('mesure_prevention', models.TextField()),
                ('danger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.danger')),
            ],
        ),
        migrations.AddField(
            model_name='danger',
            name='famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.famille'),
        ),
        migrations.AddField(
            model_name='danger',
            name='service',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.services'),
        ),
        migrations.AddField(
            model_name='danger',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.site'),
        ),
        migrations.CreateModel(
            name='ArretTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arret', models.BooleanField()),
                ('CMI_volet_recup', models.CharField(max_length=50)),
                ('date_debut_arret', models.DateField()),
                ('date_fin_arret', models.DateField()),
                ('duree_arret', models.IntegerField()),
                ('prolongation', models.BooleanField()),
                ('duree_total_pro', models.IntegerField()),
                ('rechute', models.BooleanField()),
                ('duree_total_rechute', models.IntegerField()),
                ('duree_total_arret', models.IntegerField()),
                ('evenement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.evenements')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyseEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.TextField()),
                ('probabilite', models.IntegerField()),
                ('frequences', models.IntegerField()),
                ('severite', models.IntegerField()),
                ('niveau_risque', models.IntegerField()),
                ('arbe_cause', models.TextField()),
                ('danger_lie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.danger')),
                ('evenement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.evenements')),
            ],
        ),
        migrations.AddField(
            model_name='actions',
            name='analyse_cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.analyseevenement'),
        ),
        migrations.AddField(
            model_name='actions',
            name='assigne_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.utilisateur'),
        ),
        migrations.AddField(
            model_name='actions',
            name='danger',
            field=models.ManyToManyField(to='QHSEApi.danger'),
        ),
        migrations.AddField(
            model_name='actions',
            name='evenement',
            field=models.ManyToManyField(to='QHSEApi.evenements'),
        ),
        migrations.AddField(
            model_name='actions',
            name='processus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.processus'),
        ),
        migrations.AddField(
            model_name='actions',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.site'),
        ),
        migrations.CreateModel(
            name='ChefServices',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='QHSEApi.utilisateur')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.services')),
            ],
            bases=('QHSEApi.utilisateur',),
        ),
    ]
