# Generated by Django 4.2 on 2023-05-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QHSEApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='nc',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, to='QHSEApi.nc'),
        ),
    ]
