# Generated by Django 4.2 on 2023-05-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QHSEApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
