# Generated by Django 4.1.7 on 2023-03-29 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QHSEApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processus',
            name='processus_nom',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='NC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255)),
                ('domaine', models.CharField(max_length=255)),
                ('date_nc', models.DateField()),
                ('date_prise_en_compte', models.DateField()),
                ('description_detailee', models.TextField()),
                ('annee', models.PositiveIntegerField()),
                ('mois', models.CharField(max_length=255)),
                ('detail_cause', models.CharField(max_length=255)),
                ('delai_prevu', models.DateField()),
                ('type_cause', models.CharField(max_length=255)),
                ('cout', models.FloatField(max_length=100)),
                ('progress', models.FloatField(max_length=100)),
                ('etat', models.BooleanField()),
                ('info_complementaires', models.TextField()),
                ('piece_jointe', models.FileField(default=None, null=True, upload_to='uploads/')),
                ('frequence', models.BooleanField()),
                ('gravite', models.BooleanField()),
                ('action_immediate', models.BooleanField()),
                ('nc_cloture', models.BooleanField()),
                ('processus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.processus')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.site')),
            ],
        ),
    ]
