# Generated by Django 4.1.7 on 2023-07-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QHSEApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationdanger',
            name='frequences_exposition',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='evaluationdanger',
            name='probabilite',
            field=models.FloatField(),
        ),
    ]
