# Generated by Django 4.0.8 on 2023-07-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QHSEApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
