# Generated by Django 4.2 on 2023-04-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QHSEApi', '0002_alter_actions_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='etat',
            field=models.CharField(default='Non commencé', max_length=150),
        ),
    ]
