# Generated by Django 4.1.7 on 2023-03-29 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QHSEApi', '0002_processus_processus_nom_nc'),
    ]

    operations = [
        migrations.AddField(
            model_name='nc',
            name='responsable_traitement',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='QHSEApi.utilisateur'),
        ),
    ]
