# Generated by Django 4.1.7 on 2023-03-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("QHSEApi", "0002_commande_fichetechnique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="type_auth",
        ),
    ]
