# Generated by Django 4.1.7 on 2023-03-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QHSEApi", "0003_remove_commande_type_auth"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichetechnique",
            name="fichier",
            field=models.FileField(default=None, null=True, upload_to="uploads/"),
        ),
    ]
