# Generated by Django 4.1.7 on 2023-04-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("QHSEApi", "0004_fichetechnique_fichier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichetechnique",
            name="url_fiche",
        ),
    ]
