# Generated by Django 4.1.7 on 2023-04-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QHSEApi', '0005_documentutilities_fournisseur_traitement_nc_and_more'),
        ('QHSEApi', '0005_remove_fichetechnique_url_fiche'),
    ]

    operations = [
    ]
