# Generated by Django 4.1.7 on 2023-04-07 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("QHSEApi", "0006_secteurs_alter_fichetechnique_fichier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id_document", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                ("codification", models.CharField(max_length=255)),
                ("version", models.IntegerField()),
                ("date_approbation", models.DateField()),
                ("date_previsionnelle", models.DateField()),
                ("nv_version", models.BooleanField()),
                ("type_docs", models.CharField(max_length=255)),
                ("url_document", models.FileField(upload_to="documents/")),
                ("icon", models.CharField(max_length=255)),
                (
                    "processus_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QHSEApi.processus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Historique_Document",
            fields=[
                ("id_historique", models.AutoField(primary_key=True, serialize=False)),
                ("version", models.CharField(max_length=255)),
                ("description_modification", models.CharField(max_length=255)),
                (
                    "id_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QHSEApi.document",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QHSEApi.utilisateur",
                    ),
                ),
            ],
        ),
    ]
