# Generated by Django 4.1.7 on 2023-04-04 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QHSEApi', '0006_merge_20230404_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichetechnique',
            name='fichier',
            field=models.FileField(default=None, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])]),
        ),
    ]
