# Generated by Django 4.1.7 on 2023-04-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("QHSEApi", "0007_document_historique_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historique_document",
            name="id_document",
        ),
        migrations.RemoveField(
            model_name="historique_document",
            name="modifie_par",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.DeleteModel(
            name="Historique_Document",
        ),
    ]
