# Generated by Django 4.1.7 on 2023-04-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("QHSEApi", "0008_remove_historique_document_id_document_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("codification", models.CharField(max_length=255)),
                ("version", models.IntegerField()),
                ("date_approbation", models.DateField()),
                ("date_previsionnelle", models.DateField()),
                ("nv_version", models.BooleanField()),
                ("type_docs", models.CharField(max_length=255)),
                ("url_document", models.FileField(upload_to="documents/")),
                ("icon", models.CharField(max_length=255)),
                (
                    "processus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QHSEApi.processus",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="secteurs",
            name="documents",
            field=models.ManyToManyField(to="QHSEApi.document"),
        ),
        migrations.AddField(
            model_name="site",
            name="documents",
            field=models.ManyToManyField(to="QHSEApi.document"),
        ),
    ]
